### ISSUE TITLE
which version of appium should I install?

### ISSUE THREAD

**Issue by x4evexnol** [H2SO4T/ARES#15]

**Comment by H2SO4T** [comment]
Dear @shiyuanxiang you can use the latest version available of Appium, I already know know that there is a deprecation warning. However ARES should work fine.

**Comment by x4evexnol** [comment]
Thanks! But the latest version of appium doesn't surpport the api "self.driver.find_elements_by_class_name(tag)"(RL_application_env.py:441), and got the error while running. What should I do?

2022-10-12 17:55:11.963 | ERROR    | rl_interaction.RL_application_env:manager:504 - E: Message: Locator Strategy 'name' is not supported for this session
Stacktrace:
InvalidSelectorError: Locator Strategy 'name' is not supported for this session
    at AndroidUiautomator2Driver.validateLocatorStrategy (C:\Users\syx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:393:13)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\syx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:31:8)
    at AndroidUiautomator2Driver.findElements (C:\Users\syx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:63:21)

**Comment by H2SO4T** [comment]
Which version of Appium are you using?

**Comment by x4evexnol** [comment]
1.22.3

**Comment by x4evexnol** [comment]
I've solved the problem by changing the Appium-Python-Client version to 1.0.2. Thank for your answer!
